version: '2'
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: design_project_b23_db
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8787:8080"
