# Your workflow name.
name: Run tests.

# Run workflow on every push to master branch.
on:
  push:

# Your workflows jobs.
jobs:
  pytest-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Pipenv
        run: |
          python3.9 -m pip install pipenv

      - name: Install our code as a package
        run: |
          python3.9 -m pipenv install -e . 

      - name: Install requirements
        run: |
          python3.9 -m pipenv install --deploy --ignore-pipfile --dev
#      - name: Install pytest
#        run: |
#          python -m pip install pytest

      - name: Run pytest
        run: |
          python3.9 -m pipenv run pytest src/webapp/tests/
