# Your workflow name.
name: Run tests.

# Run workflow on every push to master branch.
on:
  push:

# Your workflows jobs.
jobs:
  pytest-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install pytest


      - name: Run pytest
        run:  pytest tests/
